// Auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Products
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SINGLE_PRODUCTS = "GET_SINGLE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
